# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180502_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Colección', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'verbose_name': 'Tipo'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='available',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Collection', verbose_name='colección'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Course', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Kind', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='url',
            field=models.URLField(verbose_name='link'),
        ),
    ]
