# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180503_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pdf',
            name='topic',
            field=models.ManyToManyField(to='books.Topic', verbose_name='tema'),
        ),
    ]
